version: '3'

services:
  fastapi-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

  fastapi-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
